vsphere_datacenter = "Amsterdam"
vsphere_datastore = "HX-ACI" 
vsphere_resource_pool = "HX-ACI/Resources"
vsphere_folder = "PVT-EMEAR"
vsphere_vm_portgroup = "vm-network-98"
vsphere_vm_name = "prod-app-tfcb"
vsphere_vm_template = "Ubuntu Workstation ACI"
